# Generated by Django 2.0.3 on 2018-05-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(default='AAA', max_length=250),
        ),
    ]
