# Generated by Django 2.0.3 on 2018-05-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_user_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(max_length=250),
        ),
    ]
