# Generated by Django 2.0.3 on 2018-05-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(),
        ),
    ]
